[build]
  command = "npm install && npm run build"
  publish = "build/"
  functions = "functions/"
    environment = { NODE_VERSION = "16.4.1" }

[[plugins]]
node_bundler = "esbuild"
package = "@netlify/plugin-functions-install-core"